<?php
// 4 dilli PHP metinleri (kaynak: strings.json)
// OTOMATIK URETILDI — elle duzenlemeyin; kaynak dosyayi degistirip build.py calistirin.
return json_decode(<<<'VERI'
{
 "fr": {
  "succ_paid_t": "Paiement reçu, réservation confirmée",
  "succ_paid_d": "Merci ! Nous avons bien reçu votre acompte. Vous recevrez la confirmation par e-mail dans quelques instants. Le solde, {rest}, se règle au chauffeur.",
  "succ_pending_t": "Paiement en cours de traitement",
  "succ_pending_d": "Votre paiement est en cours de vérification. Cette page se met à jour automatiquement ; vous recevrez l'e-mail de confirmation dès validation.",
  "succ_fail_t": "Le paiement n'a pas abouti",
  "succ_fail_d": "Aucun montant n'a été débité. Vous pouvez réessayer ou confirmer votre réservation par WhatsApp.",
  "succ_ref": "Référence : {ref}",
  "succ_home": "Retour au site",
  "succ_retry": "Réessayer le paiement",
  "succ_wa": "Confirmer par WhatsApp",
  "em_subject": "Votre réservation Europa Taxi · {ref}",
  "em_heading": "Réservation confirmée",
  "em_intro": "Bonjour {name}, nous avons bien reçu votre acompte. Voici le récapitulatif de votre trajet :",
  "em_ref": "Référence",
  "em_route": "Trajet",
  "em_date": "Départ",
  "em_return": "Retour",
  "em_vehicle": "Véhicule",
  "em_pax": "Passagers",
  "em_bags": "Bagages",
  "em_paid": "Acompte payé",
  "em_due": "À payer au chauffeur",
  "em_cancel_t": "Conditions d'annulation",
  "em_outro": "Une question, un changement ? Répondez à cet e-mail ou écrivez-nous sur WhatsApp au {phone}.",
  "cancel_policy": "Annulation à plus de 24 heures du départ : remboursement intégral. À moins de 24 heures du départ, l'acompte n'est pas remboursé.",
  "dt_join": "{date} à {time}",
  "err_t": "Réservation impossible",
  "err_pay": "Le paiement n'a pas pu être initialisé. Réessayez dans un instant ou confirmez votre réservation par WhatsApp.",
  "err_km": "Distance invalide. Recalculez le prix sur le formulaire, puis réessayez.",
  "err_back": "Retour au formulaire",
  "val_route": "Veuillez indiquer l'adresse de départ et l'adresse d'arrivée.",
  "val_date": "Veuillez choisir la date et l'heure de départ.",
  "val_name": "Veuillez indiquer votre nom (2 caractères minimum).",
  "val_email": "Veuillez indiquer une adresse e-mail valide.",
  "val_phone": "Veuillez indiquer un numéro de téléphone valide (8 chiffres minimum).",
  "veh_eco_name": "Économie",
  "veh_eco_model": "Tesla Model 3",
  "veh_wagon_name": "Break",
  "veh_wagon_model": "Grand volume de coffre",
  "veh_vip_name": "Business / VIP Van",
  "veh_vip_model": "Mercedes Vito"
 },
 "nl": {
  "succ_paid_t": "Betaling ontvangen, reservering bevestigd",
  "succ_paid_d": "Bedankt! Uw voorschot is betaald. U ontvangt zo meteen de bevestiging per e-mail. De rest, {rest}, betaalt u aan de chauffeur.",
  "succ_pending_t": "Betaling wordt verwerkt",
  "succ_pending_d": "Uw betaling wordt gecontroleerd. Deze pagina wordt automatisch bijgewerkt; u ontvangt de bevestigingsmail zodra alles in orde is.",
  "succ_fail_t": "De betaling is niet gelukt",
  "succ_fail_d": "Er werd niets aangerekend. U kunt het opnieuw proberen of uw reservering via WhatsApp bevestigen.",
  "succ_ref": "Referentie: {ref}",
  "succ_home": "Terug naar de site",
  "succ_retry": "Opnieuw proberen",
  "succ_wa": "Bevestigen via WhatsApp",
  "em_subject": "Uw reservering Europa Taxi · {ref}",
  "em_heading": "Reservering bevestigd",
  "em_intro": "Dag {name}, uw voorschot is goed ontvangen. Hier is het overzicht van uw rit:",
  "em_ref": "Referentie",
  "em_route": "Rit",
  "em_date": "Vertrek",
  "em_return": "Terug",
  "em_vehicle": "Wagen",
  "em_pax": "Passagiers",
  "em_bags": "Bagage",
  "em_paid": "Voorschot betaald",
  "em_due": "Te betalen aan de chauffeur",
  "em_cancel_t": "Annuleringsvoorwaarden",
  "em_outro": "Een vraag of een wijziging? Antwoord op deze e-mail of stuur ons een WhatsApp op {phone}.",
  "cancel_policy": "Annuleert u meer dan 24 uur voor vertrek, dan wordt het voorschot volledig terugbetaald. Minder dan 24 uur voor vertrek wordt het voorschot niet terugbetaald.",
  "dt_join": "{date} om {time}",
  "err_t": "Reservering niet gelukt",
  "err_pay": "De betaling kon niet worden opgestart. Probeer het zo meteen opnieuw of bevestig uw reservering via WhatsApp.",
  "err_km": "Ongeldige afstand. Bereken de prijs opnieuw op het formulier en probeer het nog eens.",
  "err_back": "Terug naar het formulier",
  "val_route": "Geef het vertrek- en het aankomstadres in.",
  "val_date": "Kies de vertrekdatum en het vertrekuur.",
  "val_name": "Geef uw naam in (minstens 2 tekens).",
  "val_email": "Geef een geldig e-mailadres in.",
  "val_phone": "Geef een geldig telefoonnummer in (minstens 8 cijfers).",
  "veh_eco_name": "Economy",
  "veh_eco_model": "Tesla Model 3",
  "veh_wagon_name": "Break",
  "veh_wagon_model": "Extra grote koffer",
  "veh_vip_name": "Business / VIP Van",
  "veh_vip_model": "Mercedes Vito"
 },
 "en": {
  "succ_paid_t": "Payment received, booking confirmed",
  "succ_paid_d": "Thank you! We've received your deposit. A confirmation email is on its way. The rest, {rest}, is paid to your driver.",
  "succ_pending_t": "Payment being processed",
  "succ_pending_d": "Your payment is being verified. This page refreshes automatically; you will receive the confirmation email as soon as the payment clears.",
  "succ_fail_t": "The payment did not go through",
  "succ_fail_d": "You have not been charged. You can try again or confirm your booking on WhatsApp.",
  "succ_ref": "Reference: {ref}",
  "succ_home": "Back to the site",
  "succ_retry": "Try again",
  "succ_wa": "Confirm on WhatsApp",
  "em_subject": "Your Europa Taxi booking · {ref}",
  "em_heading": "Booking confirmed",
  "em_intro": "Hello {name}, we've received your deposit. Here is a summary of your ride:",
  "em_ref": "Reference",
  "em_route": "Trip",
  "em_date": "Pickup",
  "em_return": "Return",
  "em_vehicle": "Vehicle",
  "em_pax": "Passengers",
  "em_bags": "Luggage",
  "em_paid": "Deposit paid",
  "em_due": "Due to the driver",
  "em_cancel_t": "Cancellation terms",
  "em_outro": "Questions or changes? Reply to this email or message us on WhatsApp: {phone}.",
  "cancel_policy": "Cancel more than 24 hours before departure: full refund. Less than 24 hours before departure, the deposit is non-refundable.",
  "dt_join": "{date} at {time}",
  "err_t": "Booking could not be completed",
  "err_pay": "The payment could not be initialised. Try again in a moment or confirm your booking on WhatsApp.",
  "err_km": "Invalid distance. Recalculate the price on the form and try again.",
  "err_back": "Back to the form",
  "val_route": "Please enter both the pickup and the drop-off address.",
  "val_date": "Please choose the pickup date and time.",
  "val_name": "Please enter your name (at least 2 characters).",
  "val_email": "Please enter a valid email address.",
  "val_phone": "Please enter a valid phone number (at least 8 digits).",
  "veh_eco_name": "Economy",
  "veh_eco_model": "Tesla Model 3",
  "veh_wagon_name": "Station Wagon",
  "veh_wagon_model": "Extra-large boot",
  "veh_vip_name": "Business / VIP Van",
  "veh_vip_model": "Mercedes Vito"
 },
 "tr": {
  "succ_paid_t": "Ödeme alındı, rezervasyon onaylandı",
  "succ_paid_d": "Teşekkürler! Kaporanız ödendi. Onay e-postanız birazdan gelecek. Kalan {rest} şoföre ödenir.",
  "succ_pending_t": "Ödeme işleniyor",
  "succ_pending_d": "Ödemeniz doğrulanıyor. Bu sayfa otomatik yenilenir; işlem tamamlanınca onay e-postası gelecek.",
  "succ_fail_t": "Ödeme tamamlanamadı",
  "succ_fail_d": "Hesabınızdan para çekilmedi. Tekrar deneyebilir veya rezervasyonu WhatsApp'tan onaylayabilirsiniz.",
  "succ_ref": "Referans: {ref}",
  "succ_home": "Siteye dön",
  "succ_retry": "Tekrar dene",
  "succ_wa": "WhatsApp ile onayla",
  "em_subject": "Europa Taxi rezervasyonunuz · {ref}",
  "em_heading": "Rezervasyon onaylandı",
  "em_intro": "Merhaba {name}, kaporanız alındı. Yolculuğunuzun özeti:",
  "em_ref": "Referans",
  "em_route": "Güzergâh",
  "em_date": "Alış",
  "em_return": "Dönüş",
  "em_vehicle": "Araç",
  "em_pax": "Yolcu",
  "em_bags": "Valiz",
  "em_paid": "Ödenen kapora",
  "em_due": "Araçta ödenecek",
  "em_cancel_t": "İptal koşulları",
  "em_outro": "Soru veya değişiklik için bu e-postayı yanıtlayın ya da {phone} numaralı WhatsApp hattımıza yazın.",
  "cancel_policy": "Rezervasyona 24 saatten fazla süre varken yapılan iptallerde tam iade. Son 24 saat içinde kapora iade edilmez.",
  "dt_join": "{date}, saat {time}",
  "err_t": "Rezervasyon tamamlanamadı",
  "err_pay": "Ödeme başlatılamadı. Birazdan tekrar deneyin ya da rezervasyonu WhatsApp'tan onaylayın.",
  "err_km": "Geçersiz mesafe. Formda fiyatı yeniden hesaplayıp tekrar deneyin.",
  "err_back": "Forma dön",
  "val_route": "Lütfen alış ve varış adresini girin.",
  "val_date": "Lütfen alış tarihi ve saatini seçin.",
  "val_name": "Lütfen adınızı girin (en az 2 karakter).",
  "val_email": "Lütfen geçerli bir e-posta adresi girin.",
  "val_phone": "Lütfen geçerli bir telefon numarası girin (en az 8 rakam).",
  "veh_eco_name": "Ekonomi",
  "veh_eco_model": "Tesla Model 3",
  "veh_wagon_name": "Station Wagon",
  "veh_wagon_model": "Ekstra geniş bagaj",
  "veh_vip_name": "Business / VIP Van",
  "veh_vip_model": "Mercedes Vito"
 }
}
VERI, true);
